### ISSUE TITLE
(iOS)Subscription and Unsubscription is not working in in wonder push

### ISSUE THREAD

**Issue by milan-galitein** [wonderpush/wonderpush-ios-sdk#14]
Hello,

I login with the User1 and User1 has been successfully Subscribe in wonder push.
I logout with the User1 and User1 has been successfully Unsubscribe in wonder push

I login with the User2 and User2 has been successfully Subscribe in wonder push.
I logout with the User2 and User2 has been **NOT Unsubscribe** in wonder push

If i have been switching multiple account frequently then Subscription and Unsubscription is not working with Wonderpush.

Can anyone help me.

**Comment by FredMahe** [comment]
Hi Milan,

I think in your simulations you switch too quickly from user1 to user2 and the associated events are probably arriving on the server side in a messy order. When you switch from user1 to user2, it makes several operations on server side which need index refreshes, and this operation can take 15 seconds max. 
So try to make tests with letting 15 seconds between switching and tell us if it still happens. 

Best

**Comment by milan-galitein** [comment]
Hello @FredMahe  
Thanks for your reply.

I am already waiting 50to60 sec between switching.

**Comment by ofavre** [comment]
To recap, you are doing:

1. Start the freshly installed application.
2. Initialize WonderPush.
3. Accept push notification.
4. Wait 15+ seconds.
5. See an installation (A) created for your device, with no associated userId. This installation is opt-in.
6. Call `setUserId("User1")`.
7. Wait 15+ seconds.
8. See an installation (B) created for the same device, with userId `User1`. This installation is opt-in.
9. The installation A is now opt-out.
10. Call `setUserId(null)`.
11. Wait 15+ seconds.
12. The installation A is now opt-in.
13. The installation B is now opt-out.
14. Call `setUserId("User2")`
15. Wait 15+ seconds.
16. See an installation (C) created for the same device, with userId `User2`. This installation is opt-in.
17. The installation A is now opt-out.
18. The installation B is still opt-out.
19. Call `setUserId(null)`.
20. Wait 15+ seconds.
21. The installation A is still opt-out.
22. The installation B is still opt-out.
23. The installation C is now opt-out.

What you are reporting is that the last point 23 is false. Am I right?

**Comment by milan-galitein** [comment]
Yes for 23 is opt-out and in some case 22 is in opt-in

**Comment by milan-galitein** [comment]
@ofavre Have you checked it?

**Comment by milan-galitein** [comment]
@ofavre  We are still waiting your response.

**Comment by ofavre** [comment]
Hi @milan-galitein,

How often are you experiencing that point 23 is false?
How often are you experiencing that point 22 is false?

Can you do the following:

1. Activate verbose logging by calling `WonderPush.setLogging(true)` **before** calling `WonderPush.setClientId(, secret:)`.
2. Uninstall the application.
3. Run the application on a physical device through Xcode, to gather console logs.
4. Perform the 23 reproduction steps of my previous message.
  If possible can you write within the console output your actions so that it's easier to follow what you are doing.
5. Send me the device logs gathered in Xcode at <my firstname>@wonderpush.com, mentioning this issue.

Thanks in advance.

**Comment by ofavre** [comment]
This issue has been stale for almost 2 years, I'm closing it.
